name: Backlog Pipeline

on:
  # push:
  #   branches:
  #     - dev
  #     - workflow
  #   paths:
  #     - 'backlog/**'
  workflow_run:
    workflows: ["Lambda Layer Pipeline"]
    types:
      - completed


jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Build
      run: echo "Building the project..."

# jobs:
#   dev-use1:
#     uses: ./.github/workflows/tfapply.yml
#     with:
#       data-pipeline: backlog
#       environment: dev
#       aws-env-dir: dev-use1
#       aws-region: us-east-1

  
  # dev-usw2:
  #   # base_ref is the target branch
  #   if: github.event_name == 'pull_request' && github.event.base_ref == 'main'
  #   uses: ./.github/workflows/tfapply.yml
  #   with:
  #     environment: prod # Change this to 'review' or 'prod' as needed
  #     aws-env-dir: dev-usw2
  #     aws-region: us-west-2
