name: Publish Lambda Layer Version

on:
  push:
    branches:
      - devv
    paths:
      - 'lambda-layer/requirements.txt'

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash


jobs:
  dev-use1:
    uses: ./.github/workflows/publish-layer.yml
    with:
      environment: dev
      aws-region: us-east-1
